<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_job</name>
   <tag></tag>
   <elementGuidId>72de3ac0-3bd1-4491-86bc-a46d80120fb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>co.olivemedia.hihoandroidwebapp:id/tv_user_profile_email_address</value>
   </webElementProperties>
</WebElementEntity>
